### ISSUE TITLE
What kind of feature is suitable for this scenery? (deal with synonym)

### ISSUE THREAD

**Issue by guotong1988** [Wrosinski/Kaggle-Quora#1]
Train data: `Who is Michael Jordan? ` and `Who is Air Jordan? ` are one right match.
The test data is `Who is Jumpman Jordan? ` and `Who is Air Jordan? `

What feature should I add for training? Can the model capture the match info for this case?

Thank you！！！
@Wrosinski

**Comment by Wrosinski** [comment]
Best to take a look at the Extraction - Kernel Features 14.05.ipynb notebook. Features capturing straight text similarities (similar words etc) are mostly there.
